### PR TITLE
Sidebar Update

### PR DESCRIPTION
**Pull request by jordikitto**
Hey David, thanks for the excellent work on creating this widget, it's the one and only widget I use because it's absolutely essential for helping me stay organised and have an overview of what I need to do!

Anyway, since I love it and use it so much, I've extended it over the past year. 

Whilst the design change is pretty simple, I've also added a listsToNotShow array, just a slight different take one what you implemented, a listsToShow array (or something by that name). It's just my personal opinion that a user is more likely to need to edit the array less, if they only need to hide specific lists.

Another addition is changing how the due dates are displayed, I've updated it to have a more of a natural language sense, and to be simpler to read. I don't know how well this will work internationally, but I have added functionality for switching between dd/mm/yyyy and mm/dd/yyyy easily, so hopefully that helps.

Lastly I did remove the blur, as much as I love it because it looks amazing, it was very buggy for me, and I don't think most users would like that. What are your thoughts and experiences with it? I'd love to be able to get it to work consistently.

I'd love to hear what you think and if you'd like to merge. If not, I was gonna see about getting my forked version on the Ubersicht gallery (with appropriate accreditation to you of course).

Cheers, Jordi

### CODE REVIEW

**Comment by davidlday** [comment]
Hi Jordi!

I've taken a cursory look and love what I see. I probably won't get a chance to get a closer look until this weekend, but my thoughts as of now are to merge and add you as co-author. If you have a strong desire to fork and publish separately, though, I'm supportive.

Regarding the blur effect, I haven't taken a close enough look, but I think if it could be turned into an option, I'd prefer that. I'm not married to keeping the blur effect, but I think that should stay a choice if possible. To be honest, sometimes the widget gets a little lost in my rotating background as well.

I currently have an open issue in pending.sh that I want to fix first. There's no code conflict with your merge, just a time constraint on my part. I'll get back to your merge request as soon as I can.

Thanks for the contribution!
- D

**Comment by jordikitto** [comment]
Well Felix (creator of Ubersicht) says if you make additions to a widget, you should create a pull request on that widget's git, instead of adding another similar widget to the widget gallery.

Nonetheless I'm happy to merge and be added as a co-author.

Blur as an option would be better. Same for the `font-size: 10pt` or `font-size: 11pt`, because I found 10pt looks good on Retina screens, whilst 11pt works with non-Retina. So a bool like haveRetinaScreen up the top with the other configuration variables would be nifty. I did try some stuff with a CSS variable but I got a bit lost in the scope of how widgets pass/handle things.

I know for us coders it's a very simple thing to change ourselves, but I'd like to keep things as simple as possible so that friends and family can make use of the widget as well.

Looking forward to hearing what you think about it on the weekend

**Comment by jordikitto** [comment]
*bump*

**Comment by davidlday** [comment]
Hey - I'm still trying to resolve the current open issue. What appeared simple may not be so simple.

**Comment by davidlday** [comment]
So sorry for the delay. I think I have the other issue fixed now, waiting for tests before pushing. Appreciate the patience.

**Comment by jordikitto** [comment]
Cheers! Looking forward to it

**Comment by davidlday** [comment]
Hey Jordo - 

Between your PR and the two open issues, I've come to realize this project could use some restructuring. I've figured out how to put the style in an external stylesheet rather than embedded in the coffee script. I also want to move all work on the code to a develop branch to use a more git-flow style of maintenance. Trying to fix the current issue(s) and balance the PR on a single branch has been - well, it's not difficult but it certainly is causing my OCD to kick in.

I definitely want your changes integrated, but I'm inclined to cancel this PR and have you wait until I have the code restructured and have a proper develop branch, which I can get done within a week's time. Would you have any problems with this?

D

**Comment by jordikitto** [comment]
Hey David,

Would you be ok with merging the PR and restructuring the code after? I've been hoping to get the PR accepted so that friends and family can easily download the widget from the ubersicht gallery, so this way my changes get applied earlier and the code still gets restructured?

As opposed to restructuring, then me having to restructure my code as well, and then doing a PR.

Are the pending issues only to do with the .sh file?

**Comment by davidlday** [comment]
I think I can accept most of the PR without issue before restructuring. Let me take another look, but expect at the very least that the zip file will need some work prior to accepting.

**Comment by davidlday** [comment]
Okay, I'm going to have to do some quick cleanup after to get the .sh into the zip, but I can accept as-is and refactor the rest later. I can't do it tonight due to some things I need to get done for the day job tomorrow, but I should be able to merge and fix the .zip tomorrow. And seriously, I apologize for the delays. Your changes are more than welcome, but I'm being a little meticulous in keep the zip aligned with your changes and changes to the .sh. Part of the refactoring will include creating a develop branch, sans the .zip, and creating the .zip as part of a release process to avoid this kind of situation in the future.

**Comment by jordikitto** [comment]
Ok, I'm not too fussed in waiting if it will make things easier for the future. So I'm easy, there's nothing you need me to do?

**Comment by davidlday** [comment]
Nope, I got this. Thanks for the offer, tho! I could use your help testing out the new changes I'll be making, if you're game.

**Comment by davidlday** [comment]
Done!

**Pull request merged**
